config/routes.rb
Critters::Application.routes.draw do

  resources :breeding

  resources :critters

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  match '/about' => 'pages#about'
  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :critters, :dependent => :destroy

  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

# == Schema Information
#
# Table name: users
#
#  id            :integer         not null, primary key
#  username      :string(255)
#  email         :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    # TODO: Fix validation on update.
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @critters = @user.critters
    @title = 'Player: ' + @user.username
  end

  def index
    @users = User.all
    @title = 'Players'
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for( user, options = { :size => 50 } )
    gravatar_image_tag(user.email.downcase, 
                       :alt => user.username,
                       :class => 'gravatar',
                       :gravatar => options)
  end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit(@user.new_record? ? "Sign up" : "Update") %></div>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to gravatar_for(user) + content_tag(:span, user.username), user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

app/views/users/show.html.erb
<% if logged_in? && current_user == @user %>
  <div class="user_controls right">
    <p class="edit_profile"><%= link_to "Edit profile", edit_current_user_path, :class => 'button' %></p>
  </div>
<% end %>
<%= gravatar_for @user, { :size => 100 } %>
<small>Set your <a href="http://gravatar.com" target="_blank">Gravatar</a></small>
<h1><%= @user.username %></h1>
<p>E-mail: <%= @user.email %></p>
<p>Player since: <%= @user.created_at.to_s(:long_ordinal) %></p>
<p>Critter count: <%= @critters.count %></p>