config/routes.rb
Critters::Application.routes.draw do

  resources :breeding

  resources :critters

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  match '/about' => 'pages#about'
  root :to => 'pages#home'

end

app/controllers/breeding_controller.rb
class BreedingController < ApplicationController
  def new
    @males = current_user.critters.where(:sex => 'M').order('level DESC, quality DESC, name ASC')
    @females = current_user.critters.where(:sex => 'F').order('level DESC, quality DESC, name ASC')
  end

  def create
    female = Critter.find(params[:female])
    male = Critter.find(params[:male])
    @child = current_user.critters.new
    @child.name = "Child"
    @child.bred = true
    @child.mother = female
    @child.father = male
    if @child.save
      redirect_to(@child, :notice => 'A new critter was bred!')
    else
      @males = current_user.critters.where(:sex => 'M').order('level DESC, quality DESC')
      @females = current_user.critters.where(:sex => 'F').order('level DESC, quality DESC')
      flash.now[:error] = 'The critters were not in the mood to breed today.'
      render :action => 'new'
    end
  end

  def index
    redirect_to new_breeding_path
  end

end

app/helpers/breeding_helper.rb
module BreedingHelper
end

app/views/breeding/new.html.erb
<% title "Breed your critters" %>

<p>Choose your critters to breed.  They are listed by level, quality and name.</p>
<%= form_tag breeding_index_path do %>
  <div class="field">
    <%= label_tag :female %>
    <%= select_tag :female, options_from_collection_for_select(@females, 'id', 'name_and_quality'), {:include_blank => true} %>
  </div>
  <div class="field">
    <%= label_tag :male %>
    <%= select_tag :male, options_from_collection_for_select(@males, 'id', 'name_and_quality'), {:include_blank => true} %>
  </div>
  <div class="actions"><%= submit_tag "Breed" %></div>
<% end %>