config/routes.rb
Critters::Application.routes.draw do

  resources :breeding

  resources :critters

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  match '/about' => 'pages#about'
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer id="footer" class="clearfix">
	<small class="copyright">&copy; 2011 Matt Findlay, Brian Bergstrom</small>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="clearfix">
  <hgroup>
    <h1>Critters</h1>
  </hgroup>

  <% if logged_in? %>
    <div id="user_panel">
      <div id="current_user_status">
        Logged in as 
        <%= link_to current_user.username, current_user %>
        , master of 
        <%= pluralize current_user.critters.count, 'critter' %>.
      </div>
      <div id="user_controls">
        <%= link_to "Log out", logout_path, :class => 'button right' %>
        <%= link_to 'Breed', new_breeding_path, :class => 'button right' %>
        <%= link_to 'Hunt', new_critter_path, :class => 'button right' %>
      </div>
    </div>
  <% end %>
	
  <nav id="nav" class="clearfix">
    <ul>
      <li><%= link_to "Home", root_path, :class => current_page_class(root_path) %></li>
      <li><%= link_to "About", about_path, :class => current_page_class(about_path)  %></li>
      <% if logged_in? %>
        <li><%= link_to "Players", users_path, :class => current_page_class(users_path) %></li>
        <li><%= link_to "Critters", critters_path, :class => current_page_class(critters_path) %> </li>
      <% else %>
        <li><%= link_to "Sign up", signup_path, :class => current_page_class(signup_path) %></li>
        <li><%= link_to "Log in", login_path, :class => current_page_class(login_path) %></li>
      <% end %>      
    </ul>
  </nav>

</header>
 

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
   <%= csrf_meta_tag %>

  <title><%= @title || 'Home' %> | Critters</title>
  <meta name="description" content="Critters domain hunting game.">
  <meta name="author" content="Brian Bergstrom, Matt Findlay">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag :defaults, :media => "all", :cache => "styles" %>
  <%= javascript_include_tag "modernizr", "respond", :cache => "modernizer-respond" %>
</head>
<body>

  <!-- START header -->
  <%= render 'layouts/header' %>
  <!-- END header -->

  <!-- START section#content -->
  <section id="content" class="clearfix <%= controller_css_class %>">
    <% unless flash.empty? %>
      <div id="flash">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <% end %>
      </div>
    <% end %>

    <% unless @title.nil? %>
      <h2 class="content-title"><%= @title %></h2>
    <% end %>

    <%= yield %>
  </section>
  <!-- END section#content -->

  <!-- START footer -->
  <%= render 'layouts/footer'%>
  <!-- END footer -->

  <%= javascript_include_tag :defaults, :cache => true %>

  <%= debug(params) if Rails.env.development? %>
	
  <script>
    var _gaq=[['_setAccount','UA-27311952-1'],['_trackPageview'],['_trackPageLoadTime']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

</body>
</html>